### ISSUE TITLE
Neuer Button, der die Änderung an Tarifen zur zugehörigen Aktivität/Offertenposition/Rechnungsposition propagiert

### ISSUE THREAD

**Issue by Toasterson** [stiftungswo/Dime#10]
Die Werte des Tarifs werden nur beim erstmaligen Verknüpfen eines Services mit einer Aktivität/Offertenposition/Rechnungsposition propagiert. Dieser Button würde die Werte manuell updaten.

![image](https://user-images.githubusercontent.com/2150982/37906026-1d7244ba-3101-11e8-846a-33ba93643f4f.png)

Eventuell eine Alternative zu #121

**Comment by tourn** [comment]
Problem wird mit #121 behoben.
