### ISSUE TITLE
Drag & Drop für Overviews mit "order"-Feld verwenden

### ISSUE THREAD

**Issue by cookiecavekeeper** [stiftungswo/Dime#105]
Reporter: Zivi

---

Momentan müssen diese Listen mühsam mit einem *Order* Feld mit einer Zahl drin sortiert werden.

**Comment by cookiecavekeeper** [comment]
Zum Anschauen:

http://code.makery.ch/library/dart-drag-and-drop/

https://pub.dartlang.org/packages/dnd

**Comment by andyundso** [comment]
Übernommen ins neue Dime:
https://github.com/stiftungswo/betterDime/issues/38
