### ISSUE TITLE
Offertenstatus Umbenennen

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#107]
Reporter: Andi

---

* Offeriert (potential + offered)
* Bestätigt (neu)
* Abgelehnt (lost)

Könnte auch ein Formular dafür erfassen, findet Andi aber nicht nötig.

**Comment by cookiecavekeeper** [comment]
In 2586535eb5a35c5c93833b3c3c1ae219b8106f65 umgesetzt
