### ISSUE TITLE
Warnung, wenn keine aktuellen Ferientage vorhanden sind

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#109]
Reporter: Andi

----

Reminder Email an swo@stiftungswo.ch & office@stiftungswo.ch, ein Monat + 3 Wochen bevor Letzte in Dime eingetragene Ferientag vorbei ist.

Cronjob auf Cyon einrichten

**Comment by cookiecavekeeper** [comment]
Implementiert in 4ced4f25

Sobald dieser commit auf prod deployed ist kann der cronjob eingerichtet werden

**Comment by tourn** [comment]
Ist im Produktivsystem im Crontab eingetragen und wird wöchentlich ausgeführt.
