### ISSUE TITLE
Soft Delete für Offerten

### ISSUE THREAD

**Issue by Toasterson** [stiftungswo/Dime#11]

**Comment by tourn** [comment]
See #22

**Comment by cookiecavekeeper** [comment]
Welche Entities sollen alle Soft-Deletes bekommen? Dadurch entstehen eventuell neue Probleme die wir ohne Soft-Deletes noch nicht hatten.

**Comment by tourn** [comment]
Die aktuell vorhandenen Soft Deletes sind laut Andi ausreichend.
