### ISSUE TITLE
Stundensaldos Ansicht: Requests optimieren

### ISSUE THREAD

**Issue by cookiecavekeeper** [stiftungswo/Dime#113]
Reporter: zivi

---

- Alle gewünschten Perioden in einem Request laden
- Verfügbare Ferien zusammen mit den Perioden laden

**Comment by andyundso** [comment]
Bei den Perioden werden die verfügbaren Ferien nun auch mitgeliefert, anstatt dies über einen separaten Call zu lösen. Die Ladezeit der Ansicht ist nun immer noch bei etwa 10 Sek., aber das ist auf die 110 aktivierten Mitarbeiter und die damit etwa 200 API-Calls zurückzuführen. Dies wird Andi aber schauen, dass diese Anzahl etwas reduziert wird. Somit sollten wir am Ende bei etwa 5 Sekunden enden.
