### ISSUE TITLE
Laden der Aktivitäten in Zeiterfassung profilen

### ISSUE THREAD

**Issue by cookiecavekeeper** [stiftungswo/Dime#114]
Reporter: Zivi

---

Lokal mit Docker for Mac braucht das Laden der Aktivitäten knapp 60 Sekunden.

Da gibt es wohl irgendwo ineffiziente Queries. Oder es liegt doch bloss an Docker File-Mounts...

**Comment by cookiecavekeeper** [comment]
Das Problem ist gut mit dem Symfony Profiler zu erkennen (unter http://localhost:3000/_profiler/ zu erreichen und unter `app/config/config_dev.yml` `only_exceptions: false` setzen)

Eigentlich wird vom QueryBuilder bloss "SELECT * FROM Entity" ausgeführt (zu sehen im `Dime\TimetrackerBundle\Handler\GenericHandler::all()`), aber danach werden noch viele Relations einerseits beim "Hydraten" (abfüllen der DB-Antwort in Objekte durch Doctrine) und beim "Serializen" (den Objekt-Tree in JSON umwandeln durch den JMS/Serializer anhand der JMS/Serializer Annotations) abgefragt.  
Dadurch werden beim Auflisten der Aktivitäten Knapp 3000 Queries abgesetzt, von denen 2600 Timeslices abrufen, die nicht mal in der Response mitgesendet werden:

![image](https://user-images.githubusercontent.com/6794804/37820428-dac4c764-2e80-11e8-91c9-9c627f087c0d.png)
![image](https://user-images.githubusercontent.com/6794804/37820610-7ec81b0e-2e81-11e8-889a-7559cc375e12.png)


Wenn man zum Beispiel den Array-Hydrator benutzt werden bloss 2 Queries durchgeführt. Allerdings ist dann die Response nicht mehr im gleichen Format.

**Comment by andyundso** [comment]
Doctrine füllt selber die Relations ab, auch wenn der JMS Serializer diese nachher entfernt. Im Timetrack Overview holt er nur noch die Aktivitäten des aktuell gewählten Projektes ab. Im Multi-TimeTrack ist die Verzögerung nicht so extrem, wie es in der TimeTrackOverview war.
