### ISSUE TITLE
Markdown Preview

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#116]
Reporter: Zivi

---

Um den Benutzern die Formatierung mit Markdown zu erleichtern, soll ein Live Preview der Formatierung im Eingabeformular angezeigt werden. Diese könnte man hinter einem "Vorschau" Button verstecken.

**Comment by cookiecavekeeper** [comment]
In 66b0ac9b85719f7b35228b037649d6d8dd6d5f80 umgesetzt
