### ISSUE TITLE
Markdown Vorschau / PDF ist inkonsistent

### ISSUE THREAD

**Issue by cookiecavekeeper** [stiftungswo/Dime#133]
Reporter: Lukas

---

Folgende Sachen werden in der Vorschau anders als im generierten PDF angezeigt:

Kursiv und fetter text:

```markdown
* foo bar
* Some ***text*** here.
```

Auflistung nach Überschrift:

```markdown
## heading
* foo bar
* bar baz
```

Ein update der jeweiligen markdown libs könnte helfen.

**Comment by andyundso** [comment]
Die PHP-Library berücksichtigt den "Markdown Extra"-Standard von Michelf (https://michelf.ca/projects/php-markdown/concepts/), während die Dart-Library +/- den Standard von Markdown.pl und Commonmark implementiert.

Für ersteren Fall gibt es in der PHP-Library keine Möglichkeit (*** bzw. ___), jedoch kennt CommonMark diese Schreibweise und zeigt diese entsprechend in der Vorschau. Beim Rendern des PDFs kann dann die PHP-Library nicht viel mit dieser Schreibweise anfangen und zeigt somit einen normalen, fetten Text an.

Der zweite Fall konnte ich nicht nachstellen. Ein Update der Librarys habe ich ebenfalls nicht gemacht.Ein Deaktvieren der CommonMark-Erweiterung bei dem Dart-Tool habe ich zwar versucht, hat jedoch keine Wirkung gezeigt.

Next Step: Info an Lukas.
