### ISSUE TITLE
Daten bei Offerte

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/Dime#144]
Reporter: Manuel Brändli

---

Beim Druck der Offerte erscheint auf der ersten Seite jeweils das Datum der letzten Revision im Dime (anstatt das Datum, wann die Offerte ausgedruckt wurde). Das Datum bzgl. bis wann die Offerte unterzeichnet werden sollte, sollte das Druckdatum + 30 Tage sein (momentan nicht klar, was genau, bei Manuel's Beispiel wurde der 2. Juni 2016 angezeigt).

**Comment by cookiecavekeeper** [comment]
Aktuell:

- Datum der Offerte, ist das Datum der letzten Änderung im Dime
- Datum bis wann Unterschrieben werden soll, ist das "Gültig bis"-Feld

-> Manu fragen ob wirklich das "Gültig bis"-Feld weg soll und neu beides vom Druckdatum abhängig ist

**Comment by andyundso** [comment]
Ab dem Druckdatum gültig bis in 30 Tagen.
