### ISSUE TITLE
Aktualisierung Symfony

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/Dime#146]
Reporter: Zivi

---

Das Symfony-Framework fürs Backend sollte aktualisiert werden. Derzeit verwenden wir Version 2.8, welche ab November 2018 nicht mehr unterhalten wird.

Symfonys Release-Cycle ist derzeit so aufgebaut, dass alle zwei Jahre eine neue Major-Version erscheint und für diese jeweils fünf Minor-Versionen erscheinen. Die letzte Minor-Version wird dann für drei Jahre supportet. Wir könnten nun auf Symfony 3.4 wechseln, und damit wäre Support bis November 2020 garantiert.

Alternativ könnten wir auch dem "Minor"-Cycle folgen. D.h., ab September 18 auf 4.2 aktualisieren, dann auf 4.3 ab März 19, bis dann im September 19 Symfony 4.4 erscheint, welches dann wieder bis September 2022 supportet wird. Dies würde die Upgrade-Arbeit in mehrere kleine Teile splitten, anstatt eine grosse Upgrade-Aktionen wie beim Sprung von LTS zu LTS.

Sehr wahrscheinlich gibt es bei den Composer-Erweiterungen auch einige Breaking-Changes wie Doctrine, welche sich derzeit auf ihr 3.x-Release bei fast allen Paketen vorbereiten, oder bei PHPUnit (5.7 -> 6.5 oder 7.2).

**Comment by demianh** [comment]
Die deprecated Warnungen aus dem Dime Repo hab ich entfernt, so dass man einfacher auf Symfony 3+ upgraden kann. Was noch fehlt sind die Money Bundles, die nicht mehr kompatibel sind. Leider kann man die nicht einfach upgraden, wahrscheinlich muss man sie ersetzen. Ich habe dies versucht, aber leider war es nicht so einfach, da diese in die SWO Organisation geklont wurden und nicht kompatible Changes mit dem originalen Repo gemacht wurden. Ich wollte dies in meinen letzten Tagen auch nicht mehr machen, da die Testabdeckung für die Dinge wie das Moneybundle nicht gut genug sind und ich dann allenfalls ein kaputtes Dime hinterlassen würde. Man würde zwar finden, wenn der Code nicht mehr läuft (falsche Codeaufrufe, Signaturen oder Imports), aber nicht, wenn er falsch läuft bzw. die Ausgaben nicht stimmen.

**Comment by andyundso** [comment]
On Hold. bis #151 gefixt ist.

**Comment by andyundso** [comment]
Gemäss Feedback von #151 wird das aktualisierte Money-Bundle erst nach Ende Jahr eingeführt. Daher das Symfony-Upgrade ebenfalls verzögert bis dann.

**Comment by andyundso** [comment]
Neues Dime löst sozusagen das Symfony-Upgrade ab, indem ein komplett neues Framework erstellt wurde.
