### ISSUE TITLE
Überarbeitung Adressen

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/Dime#158]
Reporter: Andi

---

Um alle Adressen ins Dime sauber aufzunehmen, soll die bestehende Struktur mit den Kunden / Adressen überarbeitet werden. 

Neu:
* Bei der Erfassung kann angegeben werden, ob es eine Einzelperson oder eine Firma ist.
* Bei einer Firma können allgemeine Daten abgefüllt werden (Adresse, Hauptnummer etc.) und mehrere Ansprechspersonen zugewiesen werden.
* Bei einer Einzelperson können keine Ansprechspersonen zugewiesen werden.
* Bei der Erstellung einer Offerte / Projekt / Rechnung kann, wenn eine Firma ausgewählt wird, eine Ansprechsperson ausgewählt werden.

Abklären:
* Umsetzung Datenbankstruktur für diese neue Konstellation.
* Umsetzung Migration bestehende Kundentabelle (Export, Excel-Tabelle, Import?)
* Bestehende Beziehungen zwischen der Kundentabelle sowie den angehängten Tabellen überprüfen: wo könnten Stolpersteine bestehen? Was muss neu geknüpft werden?

**Comment by andyundso** [comment]
Das wäre die Idee fürs Datenbankschema:

<img width="612" alt="bildschirmfoto 2018-08-30 um 16 08 08" src="https://user-images.githubusercontent.com/7010698/44856963-03ce5000-ac6f-11e8-8c81-8de76a2eff43.png">

Abklären mit Andi:
* Wird es zukünftig das Szenario geben, dass Rechnungen oder Offerten an eine Firma gesendet werden und nicht an eine Ansprechsperson?

Umsetzung Migration:
* Bestehende Dime-Customers-Tabelle wird im Schema belassen, und dann die Daten händisch durch die Büro-Zivis übernommen.
* Bestehende Beziehungen zu Offerten, Projekte und Rechnungen werden belassen, und die Daten händisch oder via Skript durch die Büro-Zivis angepasst.
* Der Kunden-Import wird so angepasst, dass deklariert wird, ob es sich um die Daten in der Zeile um eine Einzelperson, um eine Firma oder um eine Ansprechsperson handelt.

**Comment by jonixis** [comment]
![Customer_schema.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6017781170bb0012aa262f/125516c66e82c728ace21e0d46cb8189378d8eac9dd6ac40ac58fd956b0a65633b0ba92e7391a172fd177a5156564ff9490c0e41ffaad82ba6e56a258f585eed837f4366846c4ff8e7df46f554f832815d84bfb68b49c3ee3a26ef8c8e4a3f17050ac4.png)
![Customer_schema2.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6017781170bb0012aa262f/125516c66e82c728ace21e0d46cb8189378d8eac9dd6ac40ac58fd957b046b313916ac217586f76ae5002e005f5647ad14500b15f9fada7aa6b66f26df590fb8d13f4d68d47f40f2ecdd42e64bef62994597b7bb804dc5eb3b22e483884e3b1f0d1f9bb2.png)

**Comment by jonixis** [comment]
[Uploading Untitled-1.png...]

**Comment by jonixis** [comment]
![Untitled-1.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b6017781170bb0012aa262f/125516c66e82c728ace21e0d46dd9a8e2a968fac8ba4ee01e81fe086264c22703d46f9692584b371e6137e590b0e4baf12095f44afafdc2ea2e33c22984019af80330b2b9b645bf9fa9015ad00bd2a8a4a86b0b58849c0ed3d22e18d9d02.png)

**Comment by andyundso** [comment]
Ein erste Version ist nun auf dem Test-System. Es gibt aber noch einige TODOs:
- [ ] AbstractCustomer als Single-Table-Inheritance einrichten, und Company und Person als eigene Entität belassen. So können die 50%-Checks bei Phone und Address entfernt werden und es ist dennoch möglich, gewisse Dinge individuell zu betrachten (z.B. Firma muss eine RateGroup haben, während die Person nur eine bracht, wenn sie eine Firma hat). API-Endpunkte mit "companies" und "persons" belassen.
- [ ] Firmen können Person hinzugefügt werden, welche bereits existieren, jedoch keine Firma zugewiesen haben.
- [ ] Umkehrfunktion: Personen können aus Firmen gelöst werden.
- [ ] Beschreibung zu Adressen hinzufügen: Bereits nach zwei Adressen kann es verwirrend sein, was nun genau an welcher Adresse passiert.
- [ ] Alias, Chargeable und SystemCustomer wieder implementieren.
- [ ] Adressen Import / Export aus #136 und die Tags-Relation wieder implementieren. Dazu das CSV so verändern, dass Einzelpersonen, Firmen und Personen von Firmen sauber unterschieden werden können.
- [ ] Anpassen der Entities, welche Verbindungen zu der Kundentabelle oder den alten Adressen haben.
- [ ] Migration bestehende Kunden: Jeder Kunde und seine Adresse wird als neuer Firmenkunde erfasst. Danach Offerten / Rechnungen / Rechnungen checken, ob dort die Adresse von der Haupt-Adresse des Kunden abweicht, wenn ja, als neue Adresse erfassen. Möglichkeit im UI anbieten, dann die Firmenkunde zu einem "normalen" Kunden zu degradieren. Muss dann nach dem Release auf Prod nochmals manuell überprüft werden.

**Comment by andyundso** [comment]
Nachfragen bei Andi:
- [] Export Adressen: Für was brauchen wir Exports?

**Comment by andyundso** [comment]
Feature ist nun soweit fertig mit den letzten Überarbeitungen, folgende Schritte gibt es noch zum Abschluss:

- [ ] Feedback von Andi einholen.
- [ ] Feedback ggf. von Alex einholen (Andi fragen ob nötig).
- [ ] Import-Datei vorbereiten (etwa 50 Firmen und 50 Personen) und auf Dime-Test importieren, importierte Daten auf Vollständigkeit und Korrektheit prüfen.
- [ ] Pull-Request #178 nach Code Review von Dani über Squash + Merge in master übernehmen, FF-Merge auf production von master vornehmen.
- [ ] Kunden-Migrationsskript anstossen (app/console customers:migrate).
- [ ] Information an SWO-Mitarbeitende über die Änderungen (speziell, dass alle vorherig erfassten Kunden als "Migriert" erfasst sind und man diese Angaben, wenn man etwas im Zusammenhang mit diesem Kunden verändert, doch gleich prüfen solle).

Nachdem die Änderungen mehrere Wochen live und stabil sind, kann die alte Kunden-Entität aus dem Backend entfernt werden:

- [ ] Entity / FormType / Controller / AliceDataSet / Tests / etc. löschen.
- [ ] OldCustomer und OldAddress von Invoice / Project / Offer / .. entfernen.
- [ ] MigrateCustomerCommand entfernen.
- [ ] Neue Doctrine-Migration erstellen, um die dazugehörigen Tabellen und Spalten zu löschen.
- [ ] Neue Doctrine-Migration erstellen, um die "Customer"-Tabelle zu "customers" umzuschreiben und "new_customers_tags" zu "customers_tags".

**Comment by andyundso** [comment]
Migration wird nun über das Migrationsskript für das neue Dime gehandelt (https://github.com/stiftungswo/DimeMigration/blob/master/EntityMigrator/CustomerMigrator.php).
