### ISSUE TITLE
Neue Rechnung erstellen ohne erfasste Arbeitsstunden auf Projekt

### ISSUE THREAD

**Issue by jonixis** [stiftungswo/Dime#159]
Reporter: Violaine Leyat
---

Es trat der Fall auf, dass man Materialkosten verrechnen wollte und jedoch keine eingetragene Arbeitsstunden im entsprechenden Zeitraum existierten. Das Standardverhalten von Dime ist wie folgt: 

- Falls Stundeneinträge nach dem Enddatum der letzten Rechnung existieren -> Erstelle neue Rechnung 
- Falls **keine** Stundeneinträge nach dem Enddatum der letzten Rechnung existieren: -> Springe zu letzter Rechnung

Es wäre wünschenswert, eine neue Rechnung erstellen zu können nur für Materialkosten (ohne Arbeitsstunden).

**Comment by andyundso** [comment]
Feedback von Andi: Es soll möglich sein, dass man eine Rechnung aus einem Projekt erstellen kann, auch wenn keine neuen Stunden verbucht wurden.
