### ISSUE TITLE
Sonderzeichen im Service Rapport werden nicht dargestellt

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/Dime#161]
Reporter: Zivi

---

Siehe Screenshot. Im Dime-Menü unter Rapporte -> Services zu finden.

<img width="1121" alt="bildschirmfoto 2018-08-29 um 17 17 36" src="https://user-images.githubusercontent.com/7010698/44797527-ae7f3980-abaf-11e8-8a1a-e94cec00be8c.png">

**Comment by jonixis** [comment]
Das CSV-File wird mit folgendem Encoding exportiert: *ISO-8859-1*. Wird das encoding nicht automatisch vom Tabellenkalkulationsprogramm oder  Texteditor erkannt, muss das encoding beim Import manuell ausgewählt werden.
