### ISSUE TITLE
MWSt.-Feld verschwindet auf kleinem Bildschirm

### ISSUE THREAD

**Issue by andyundso** [stiftungswo/Dime#176]
Reporter: Lothar

---

Auf kleinen Bildschirm (15 Zoll MacBook reicht) verschwindet das Eingabefeld für die MWSt. Man sieht dann lediglich nur noch das Prozentzeichen.

**Comment by tourn** [comment]
Als workaround kann man herauszoomen, aber natürlich sollte man das Layout etwas anpassen. Mobile hat wohl dasselbe Problem?
