### ISSUE TITLE
Soft delete entries

### ISSUE THREAD

**Issue by Michael-Schaer** [stiftungswo/Dime#22]
To prevent data loss, all delete functions should use soft delete instead of actually being deleted on the database.

Most importantly this applies to "projects" and "activities"

See also #35

**Comment by tourn** [comment]
Das ist mittlerweile soweit implementiert. Bei den Services wurde sogar doppelt gemoppelt und diese können nun sowohl gelöscht als auch aktiviert werden. Der Unterschied hierbei ist, dass ein gelöschter Service komplett aus dem Interface verschwindet, während ein Archivierter Service nicht mehr in der `<service-select>` Dropdown auswählbar ist und speziell aus der Service Übersicht gefiltert werden kann.

Allgemein sind soft-gelöschte Einträge ohne Eingriff auf der Datenbank nicht widerrufbar. Eventuell sollte man die soft delete Funktion so anpassen, dass sie mehr wie die Archivierung funktioniert.

**Comment by tourn** [comment]
Soft deletes sollen sich wie Archivierung verhalten: Die DInge werden aus dropdowns ausgelassen und sind optional ausblendbar.

Komplett löschbar soll nichts sein, das kann im Notfall über die Datenbank direkt gemacht werden.

**Comment by andyundso** [comment]
Im neuen Dime werden nun alle Entitäten "Soft-Deleted".
