### ISSUE TITLE
Mitarbeiter Suchfunktion geht nur auf Email

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#29]
Originally reported by: **swo-admin NA (Bitbucket: [swo-admin](https://bitbucket.org/swo-admin), GitHub: Unknown)**

----------------------------------------

z.B. wenn man nach "Remo" sucht, findet man "Remo Schlaepfer" nicht

Aktuell ist es nach meiner Erinnerung nach Email welches zur Suche verwendet wird.

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/5

**Comment by tourn** [comment]
Zusätzlich auch Namen-Felder mit einbeziehen.
