### ISSUE TITLE
Add Keyboard Support to Overview Widgets

### ISSUE THREAD

**Issue by Toasterson** [stiftungswo/Dime#3]
For Example:
- Arrow-Up/Down for moving selection 
- ctrl and shift + Arrow Keys for Multiple selection 
- Enter to edit 
- Delete to remove 
- ctrl+Enter to duplicate ?

**Comment by tourn** [comment]
Will das jemand?

**Comment by tourn** [comment]
Wird aktuell nicht benötigt.
