### ISSUE TITLE
Bessere Fehlermeldung/Feedback nach dem Ausfüllen der Forms erhalten

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#30]
Originally reported by: **swo-admin NA (Bitbucket: [swo-admin](https://bitbucket.org/swo-admin), GitHub: Unknown)**

----------------------------------------

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/6

**Comment by tourn** [comment]
Vorerst zusätzlich ein Popup/Toast anzeigen

**Comment by tourn** [comment]
https://github.com/stiftungswo/Todo/issues/29  die Sentry-Integration des Frontends geht in eine ähnliche Richtung, vielleicht lässt sich dies gleich kombinieren.

**Comment by tourn** [comment]
Mit der ganzen Formularvalidierung aus #106 ist der Sache schon mal etwas vorgebeugt. Um sinnvolle Fehlermeldungen anzeigen zu können, müsste das Backend diese erst produzieren. Sinnvolle Fehlermeldungen aus dem Backend zu bekommen ist ein grösseres Projekt, zumal der Fehler meist ein Crash ist, an dem der Benutzer eh nichts ändern kann.
