### ISSUE TITLE
Offerte Adresse SWO ändern zu Schatzacker,

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#31]
Originally reported by: **swo-admin NA (Bitbucket: [swo-admin](https://bitbucket.org/swo-admin), GitHub: Unknown)**

----------------------------------------

Bei Offerte soll eigentlich die SWO Adresse stehen und bei der Rechnung wegen der Buchhaltung die Schatzacker genommen werden. Es wäre also praktisch wenn man die Adressen manuell im Formular auswählen könnte. Übergangsweise soll erstmal für beides Schatzacker genommen werden sofern es nicht anders geht.

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/7

**Comment by jgschwend** [comment]
see #54

**Comment by tourn** [comment]
Ist soweit erledigt. Siehe auch #87.
