### ISSUE TITLE
Tarif Stundensatz inkonsistent

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#32]
Originally reported by: **swo-admin NA (Bitbucket: [swo-admin](https://bitbucket.org/swo-admin), GitHub: Unknown)**

----------------------------------------

Wenn man bei der Rechnung die Gemeinde ODER den Kanton wählt, dieser jedoch nicht vorhanden bei der Kostenstelle ist, wird der letzte Eintrag der verwendet wurde genommen.

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/8

**Comment by tourn** [comment]
Was passiert hier? Manu Fragen.

**Comment by tourn** [comment]
Dies scheint dasselbe Problem wie #120 zu sein.
