### ISSUE TITLE
Git Submodules auf Bitbucket migrieren

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#36]
Originally reported by: **Simon Rösch (Bitbucket: [simonroesch](https://bitbucket.org/simonroesch), GitHub: [simonroesch](https://github.com/simonroesch))**

----------------------------------------

Die referenzierten Submodules sind aktuell noch auf Github

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/12

**Comment by tourn** [comment]
Wir zügeln stattdessen wieder auf Github.
