### ISSUE TITLE
Mobile Ansicht

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#38]
Originally reported by: **Michael Schär (Bitbucket: [angralon](https://bitbucket.org/angralon), GitHub: Unknown)**

----------------------------------------

Manche Einsatzleiter erfassen die Zeiten vor Ort auf dem Tablet. Dabei werden die Tabellen nicht schön skaliert.

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/14

**Comment by tourn** [comment]
Lukas scheint momentan der einzige Tablet User zu sein und sieht hier keine Probleme.
