### ISSUE TITLE
Add Multiple Selection to Overview Widgets

### ISSUE THREAD

**Issue by Toasterson** [stiftungswo/Dime#4]

**Comment by tourn** [comment]
Eine spezifische Version davon ist in https://github.com/stiftungswo/dime/blob/c4d5978bf2809b1a0ae014c955a226a915c31530/src/Dime/FrontendBundle/Resources/public/lib/src/component/overview/timeslice_overview_component.dart implementiert, jedoch könnte man vieles davon wohl in die Parent Klasse ziehen. Auch schön wäre es, die Delete Buttons aus den Zeilen zu entfernen und analog zu den  Hinzufügen/Duplizieren Buttons dazu zu tun.

**Comment by cookiecavekeeper** [comment]
Abklären:

- Ist es wirklich nötig mehrere Zeilen zu löschen / duplizieren?
- Man könnte entweder den "Löschen" Knopf aus der Zeile nehmen und zum "Duplizieren" Knopf nehmen, oder andersrum und dadurch den ganzen "Zeile auswählen" Code loswerden.

**Comment by cookiecavekeeper** [comment]
Entschieden:

 - keine Auswahl mehr mit click
 - "Duplizieren"-Button neben "Edit"-Button zügeln (Auswahl Logik entfernen)
