### ISSUE TITLE
Zeiterfassung Massenverarbeitung

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#41]
Originally reported by: **Michael Schär (Bitbucket: [angralon](https://bitbucket.org/angralon), GitHub: Unknown)**

----------------------------------------

Es kommt häufig vor, dass eine Serie von Zeiterfassungen von einem Projekt ins nächste Verschoben werden soll.

Im Moment muss dafür jede Zeiterfassung gelöscht und neu erfasst werden.

Soll: Ein Form mit Ausgangs-Projekt, Zielprojekt, Startzeit und Endzeit. Alle Zeiterfassungen zwischen Startzeit und Endzeit werden aus dem Ausgansprojekt ins Zielprojekt verschoben.

Besprochen mit Alex, Manuel

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/17

**Comment by tourn** [comment]
Hier stellt sich die Frage, ob es nicht sinnvoller ist, die bestehende Zeiterfassungs-Übersicht um Checkboxen und einen "Verschieben" Button zu erweitern, anstatt einen neuen Screen dafür einzuführen.

**Comment by tourn** [comment]
See #75

**Comment by cookiecavekeeper** [comment]
Nach Sitzung:  
Neu muss nicht mehr eine Aktivität ausgewählt werden, sondern die Aktivität wird übernommen (oder erstellt wenn sie noch nicht auf dem Ziel-Projekt existiert).

**Comment by tourn** [comment]
Luki wünscht sich die ursprüngliche Funktionalität zusätzlich - es sollen auch angewählte Timeslices auf eine andere Aktivität (in selbem oder anderem Projekt) verschoben werden können.

Wird das jetzt noch dazuimplementiert?

Dazu kommt - die Timeslice Overview hat ein deaktiviertes Dropdown für die Aktivität. Vielleicht lässt sich dieses wieder instandsetzen? (Wobei dadurch keine Batch verarbeitung ermöglicht wird)

**Comment by tourn** [comment]
Andi hat das zusätliche Implementieren vom Verschieben auf eine spezifische Aktivität abgesegnet.
