### ISSUE TITLE
Standardabzüge entfernen

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#43]
Originally reported by: **Michael Schär (Bitbucket: [angralon](https://bitbucket.org/angralon), GitHub: Unknown)**

----------------------------------------

Reporter: Andi

Die Standardabzüge können zwar hinzugefügt werden, jedoch nicht gespeichert (oder nach dem laden nicht angezeigt?).

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/19

**Comment by tourn** [comment]
Woher wird das Dropdown populiert? Braucht man das Feature überhaupt, oder kann man das mit dem "Weitere Abzüge" Feature behandeln?

**Comment by tourn** [comment]
Auf der Produktivdatenbank ist kein einzelner Standardabzug eingetragen und die Funktionalität scheint sich auch problemlos mit den Zusatzabzügen nachstellen zu lassen. Um das ganze etwas zu vereinfachen, wurden Standardabzüge aus dem UI entfernt.

(Sollten wir das wirklich so durchziehen, sollte man auch den entsprechenden Code und die Tabelle im Backend entfernen, damit wir keinen Dead Code herumliegen haben)

**Comment by tourn** [comment]
TODO: Entsprechenden Code und die Tabelle im Backend entfernen, damit wir keinen Dead Code herumliegen haben
