### ISSUE TITLE
Beim Duplizieren von Entitäten werden einige Felder nicht kopiert

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#44]
Originally reported by: **Michael Schär (Bitbucket: [angralon](https://bitbucket.org/angralon), GitHub: Unknown)**

----------------------------------------

Beim Duplizieren eines Projektes wird die Tarifgruppe nicht übernommen.

TODO:

- [x] Tarifgruppe im Projekt
- [x] Kunde in Rechnung
- [x] Kostenstellen in Rechnung

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/20

**Comment by tourn** [comment]
Der Fehler scheint im Backend zu liegen; das Feld wird beim POST nach hinten geschickt, kommt aber nicht mehr zurück.

Ebenso der `customer` beim duplizieren einer Rechnung.

**Comment by tourn** [comment]
Okay, der war wüst.

Schuld war ein zu schlauer Getter in Kombination mit der Reihenfolge, wie die Formularfelder hydriert werden: https://github.com/stiftungswo/Dime/blob/a8072af585edecf401fda12b93bf22e82a398779/src/Dime/TimetrackerBundle/Entity/Project.php#L655-L665

### Falsch
```php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('customer', 'entity', array('class' => 'DimeTimetrackerBundle:Customer'))
            ->add('rateGroup', 'entity', array('class' => 'DimeTimetrackerBundle:RateGroup'))
           //...
            ;
    }
```

Wenn das Formular wie im obigen Snippet zusammengebaut wird, dann Enthält die Project Entity schon ein Customer Objekt, wenn `rateGroup` abgefragt wird. Deshalb kommen wir in `getRateGroup` auf L662 heraus. Dies returnt ein RateGroup Objekt (bzw einen Proxy darauf), obwohl das `rateGroup` Property des Projekts `null` ist. Dies verwirrt das Symfony Form [[1]](#1), weshalb das Property ausgelassen wird.


### Richtig

```php
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('rateGroup', 'entity', array('class' => 'DimeTimetrackerBundle:RateGroup'))
            ->add('customer', 'entity', array('class' => 'DimeTimetrackerBundle:Customer'))
           //...
            ;
    }
```

Drehen wir das ganze jetzt um ist beim Aufruf von `getRateGroup` noch gar kein `customer` vorhanden, weshalb wir auf L660 herauskommen und `null` zurückbekommen. Darum setzt das `Form` nachher die richtige RateGroup.

### TL;DR
Wenn so ein "schlauer" Getter wie oben verwendet wird, dann muss das Property im entsprechenden FormType so früh wie möglich aufgelistet werden.

---

1. <span id="f1"></span> Das Symfony Form erzeugt ein leeres Project Objekt, das daraufhin mit den Werten des Formulars abgefüllt werdeN; [`PropertyPathMapper#mapFormsToData($forms, &$data)`](https://github.com/symfony/form/blob/23394a60d49d2aa904dacda6e5eb29d88251f9da/Extension/Core/DataMapper/PropertyPathMapper.php#L67) füllt die Project Entity (`$data`) mit den Werten aus `$forms` ab. Dafür wird auf L92 gecheckt: `$form->getData() !== $this->propertyAccessor->getValue($data, $propertyPath)`

`$form->getData()` ist richtigerweise ein Proxy auf ein Customer Objekt, das von Form schon herausgesucht wurde.  
`$this->propertyAccessor->getValue($data, $propertyPath)` ruft den Getter des "leeren" Objekts auf, der genau denselben Proxy zurückgibt, auch `rateGroup` eigentlich `null` ist.

Form findet nun:
> Cool, `lhs === rhs`, dann müssen wir ja auch gar nichts mehr ändern

Und `rateGroup` bleibt auf `null`.
