### ISSUE TITLE
Offerte - Services hinzufügen

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#45]
Originally reported by: **Michael Schär (Bitbucket: [angralon](https://bitbucket.org/angralon), GitHub: Unknown)**

----------------------------------------

Beim Hinzufügen von Services gibt es eine Fehlermeldung, wenn nicht alle Felder ausgefüllt sind.

Die Felder sollten als mandatory markiert werden und die null-pointers abgefangen werden.

Betroffene Tabelle: offer_positions

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/21

**Comment by tourn** [comment]
Die Felder sind seit #106 markiert und crashen tut soweit ich seh nichts mehr. Was noch besteht ist das Usabililty Problem hier: https://github.com/stiftungswo/Dime/blob/23c2d207008cf7aa1e3ba22dd624ea8bdb7b0023/src/Dime/FrontendBundle/Resources/public/lib/src/component/overview/offer_position_overview_component.html#L54-L61

Aber das ist eine Sache für sich.
