### ISSUE TITLE
Projekte archivieren

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#49]
Originally reported by: **Michael Schär (Bitbucket: [angralon](https://bitbucket.org/angralon), GitHub: Unknown)**

----------------------------------------

Ein Projekt sollte archiviert werden können, so dass es nicht mehr in der Select-Box erscheint.

Grund dafür ist, dass Projekte oft dieselben Namen haben, mit Ausnahme einer Jahrzahl. So werden die Projekte einfach verwechselt und Zeiterfassungen falsch zugeordnet.

Eine Funktion zum Anzeigen archivierter Projekte in der Projektliste wäre wünschenswert.

Zu besprechen mit Andy, Idee von Manuel und Alex

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/25

**Comment by tourn** [comment]
Zusätslich: Filter auf Projektübersicht, archivierte Projekte nur bei Bedarf einblenden.
