### ISSUE TITLE
Mehrwertsteuersatz

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#50]
Originally reported by: **Michael Schär (Bitbucket: [angralon](https://bitbucket.org/angralon), GitHub: Unknown)**

----------------------------------------

Der neue Mehrwertsteuersatz von 7.7 muss als neue option auswählbar sein. Wenn möglich nicht den alten Steuersatz (8.0) überschreiben.

Der tiefere Satz von 2.5 bleibt gliech.

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/26

**Comment by tourn** [comment]
Hab jetzt einfach die Services angepasst - Die Aktivitäten werden/wurden für die entsprechenden Projekte von Hand angepasst.
