### ISSUE TITLE
Rechnungsposten von gelöschten Aktivitäten

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#51]
Originally reported by: **Michael Schär (Bitbucket: [angralon](https://bitbucket.org/angralon), GitHub: Unknown)**

----------------------------------------

Wenn eine activity gelöscht wird, sollte bei allen verknüpften invoice_items die "activity_id" auf NULL gesetzt werden. Da dies im Moment nicht geschieht, können betroffene Rechnungen nicht geladen werden.

Dafür soll eine neue Migrationsdatei generiert werden, die die folgende Änderung vornimmt:
* Das alte foreign key constrait über table name und column name finden und löschen
* Ein neues constraint erstellen mit "ON DELETE SET NULL" (wenn möglich mit dem selben namen)

Die Änderung muss auch im model (InvoiceItems.php) und im dime.sql Script vorgenommen werden.

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/27

**Comment by tourn** [comment]
Zumal die Activities mit einem `deleted_at` Feld soft-deleted werden, bringt der Constraint nichts. Auch ist es laut Andi nicht wüschenswert, wenn Aktivitäten von einen Projekt entfernt werden, die bereits gebucht wurden.

Was wir also tun: Vor dem (soft)Löschen einer Aktivität aus einem Projekt muss überprüft werden, ob dieses Projekt Rechnungen hat, die eine Position besitzen, die auf diese Aktivität verweist.

![image](https://user-images.githubusercontent.com/2150982/32892009-1e8bdea2-cad5-11e7-89a4-16f156c09d76.png)

**Comment by tourn** [comment]
Wurde mit 284ff2993ac8554ccce21f4af3849f6231e47d01 soweit implementiert. Wäre es vielleicht Sinnvoll, auch sicherzustellen, dass keine Timeslices darauf gebucht wurden? Ansonsten verwaisen diese ja beim Löschen der Aktivität.

**Comment by tourn** [comment]
Besprechung mit Andi: Zusätzlich löschen von gebuchten Aktivitäten verhindern
