### ISSUE TITLE
Introduce Swagger for API Documentation

### ISSUE THREAD

**Issue by swoadmin** [stiftungswo/Dime#52]
Originally reported by: **Jonas Gschwend (Bitbucket: [jonasgschwend](https://bitbucket.org/jonasgschwend), GitHub: Unknown)**

----------------------------------------

As a developer I would like to get quick overview about the Dime backend by having a look at the Swagger UI.

e.g:
https://symfony.com/doc/master/bundles/NelmioApiDocBundle/swagger-support.html

----------------------------------------
- Bitbucket: https://bitbucket.org/stiftungswo/dime/issue/28

**Comment by tourn** [comment]
Wurde bereits teilweise implementiert und ist unter http://localhost:3000/api/doc einsehbar.

**Comment by andyundso** [comment]
Ich habe alle Routen nochmals mit der vorhandenen Swagger-Doku abgeglichen und alle Routen sind in Swagger erfasst.
