### ISSUE TITLE
Zusätzliche Hierarchiestufe: Unterprojekte

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#56]
Reporter: Luki

Eine zusätzliche Schicht zwischen Projekten und Aktivitäten.

![image](https://user-images.githubusercontent.com/2150982/33177140-e741ceb0-d061-11e7-9dea-cf008b9cc772.png)

Dies ermöglicht eine genauere Zeiterfassung und Abrechnung für einzelne Projektteile, was besonders bei grösseren Projekten wünschenswert ist.

**Comment by tourn** [comment]
Die Problematik hier ist, dass diese Hierarchie in die gesamte Offer-Project-Invoice Struktur eingebaut werden müsste, die schon relativ komplex ist.

Das neue *subproject* müsste mindestens zwischen *offer* - *offer_position*  und *project* - *activity* eingebaut werden, was einigen Umbauaufwand mit sich bringen würde.

![image](https://user-images.githubusercontent.com/2150982/33178382-453d2218-d066-11e7-84cd-622c82df634a.png)

@Toasterson Lukas hat gemeint, dass man sich eventuell noch mit Dir absprechen könnte, da Du  das Projekt sehr gut kennst. Kannst/magst du hierzu einen Kommentar abgeben?

**Comment by Toasterson** [comment]
@tourn Nicht Soviel studieren mit hierarchie etc. Ganz einfach ein feld im Projekt einführen wo man ein anderes projekt hinterlegen kann (self reference) und dann im frontend einfach die anzeige so bauen das es bei projekten mit subprojekt einen view anzeigt bei dem man das Subprojekt auswählt. Für queries halt einfach eine funktion machen die alle aktivitäten von allen projekten in einer liste anzeigt und dann die hierarchie rekursiv auflösen. Dann must du an der datenstruktur nichts ändern.

**Comment by Toasterson** [comment]
und eine funktion fürs verschieben damit man die aktivitäten nach dem die offerte in ein projekt umgewandelt wurde aufteilen kann resp. beim umbauen in ein invoice objekt die zwischenstufe auflösen mit der funktion zum alle aktivitäten in einem projekt und allen unterprojekten anzeigen.

**Comment by andyundso** [comment]
Wir haben dies mit Luki nochmals besprochen und besser definiert:

https://github.com/stiftungswo/betterDime/issues/34
