### ISSUE TITLE
Projeke > Zeiterfassung: Zum nächsten Eintrag Springen

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#60]
Reporter: Andi

---

Momentan kann man in der Zeiterfassung die Ansicht um einen Tag/Woche/Monat verschieben. Zusätzlich soll auch ein Pfeil erscheinen, der bis zum nächsten Eintrag springt.

**Comment by cookiecavekeeper** [comment]
Was implemented in 702348af
