### ISSUE TITLE
Fix doctrine:migrations:diff

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#66]
Mit dem aktuellen Setup ist es nicht möglich, sinvoll Migrationen mit Doctrine zu generieren.

* Die bestehenden Migrations-Files erstellen eine Datenbank, nicht mit der Produktivdatenbank übereinstimmt.
  * Der Workflow, prod auf die Entwicklerdatenbank zu spiegeln, und dann davon mit *doctrine:migrations:diff* eine Migration zu erzeugen, funktioniert nicht, da die daraus entstehende Migration nicht mit den vorherigen Migrationsdateien kompatibel ist.
* Ein Bug in Doctrine erstellt für Felder mit einer gesetzten Collation diffs, auch wenn gar nichts daran geändert wurde.

## Lösungsvorgehen: 
1. Model-Klassen ab der Produktivdatenbank generieren
2. Deren Annotations mit den bestehenden Model-Klassen abgleichen
3. Von den Model-Klassen eine neue Migration auf einer Leeren Datenbank erstellen, die jetzt hoffentlich genau den Zustand der Produktivdatenbank repräsentiert

## Alternative

Eventuell könnte man die Produktivdatenbank basierend auf den bestehenden Migrationen neu aufsetzen?

**Comment by cookiecavekeeper** [comment]
## Aktueller Stand

- Die Entwicklungs-DB aus den Doctrine-Annotations hat das Schema das wir überall erreichen wollen
- Nicht alle Änderungen an den Annotations wurden als Migration festgehalten
- Dadurch sind auch die test / produktiv Datenbanken nicht auf dem neusten Stand
- Zusätzlich wurden manuell Änderungen an den test / produktiv Datenbanken durchgeführt

## Aktuelle Lösung

- Eine Migration wurde erstellt die die Migrations auf den gleichen Stand wie die Annotations bringt 21ed9e94ada4aa2cfc7eda6b76cfa69183a1bf05
- Um die Migration auf der Test-Umgebung ausführen zu können musste ein kleines Skript vorher ausgeführt werden:

```sql
ALTER TABLE invoices DROP FOREIGN KEY FK_INVOICE_COSTGROUPS, ADD CONSTRAINT `FK_6A2F2F95CC72B005` FOREIGN KEY (`costgroup_id`) REFERENCES `costgroups` (`id`);
```

- Um die Test-Umgebung dann komplett auf den Stand der Annotations zu bringen brauchte es noch ein weiteres Skript:

```sql
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE costgroups CHANGE id id INT AUTO_INCREMENT NOT NULL;
SET FOREIGN_KEY_CHECKS = 1;
ALTER TABLE costgroups DROP FOREIGN KEY FK_CG_USER, ADD CONSTRAINT `FK_21D763E8A76ED395` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL;
ALTER TABLE invoice_costgroups DROP INDEX fk_invoice_costgroups_user_id;

ALTER TABLE invoices DROP INDEX fk_accountant_id, ADD INDEX IDX_6A2F2F959582AA74 (accountant_id);
ALTER TABLE invoices DROP FOREIGN KEY fk_accountant_id, ADD CONSTRAINT `FK_6A2F2F959582AA74` FOREIGN KEY (`accountant_id`) REFERENCES `users` (`id`) ON DELETE SET NULL;

ALTER TABLE project_categories CHANGE id id INT(11) AUTO_INCREMENT NOT NULL;

ALTER TABLE projects DROP INDEX FK_projects_project_categories, ADD INDEX IDX_5C93B3A4DA896A19 (project_category_id);
ALTER TABLE projects DROP INDEX FK_projects_accountant, ADD INDEX IDX_5C93B3A49582AA74 (accountant_id);
ALTER TABLE projects DROP FOREIGN KEY FK_projects_accountant, ADD CONSTRAINT `FK_5C93B3A49582AA74` FOREIGN KEY (`accountant_id`) REFERENCES `users` (`id`) ON DELETE SET NULL;
ALTER TABLE projects DROP FOREIGN KEY FK_projects_project_categories, ADD CONSTRAINT `FK_5C93B3A4DA896A19` FOREIGN KEY (`project_category_id`) REFERENCES `project_categories` (`id`) ON DELETE SET NULL;

ALTER TABLE services CHANGE archived archived TINYINT(1) NOT NULL;

ALTER TABLE timeslices DROP INDEX IDX_72C53BF4A76ED395, ADD INDEX IDX_72C53BF48C03F15C (employee_id);
ALTER TABLE timeslices DROP INDEX FK_timeslices_user, ADD INDEX IDX_72C53BF4A76ED395 (user_id);
ALTER TABLE timeslices DROP FOREIGN KEY FK_timeslices_employee, ADD CONSTRAINT `FK_72C53BF48C03F15C` FOREIGN KEY (`employee_id`) REFERENCES `users` (`id`) ON DELETE SET NULL;
ALTER TABLE timeslices DROP FOREIGN KEY FK_timeslices_user, ADD CONSTRAINT `FK_72C53BF4A76ED395` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE SET NULL;

ALTER TABLE users CHANGE username username VARCHAR(180) NOT NULL, CHANGE username_canonical username_canonical VARCHAR(180) NOT NULL, CHANGE email email VARCHAR(180) NOT NULL, CHANGE email_canonical email_canonical VARCHAR(180) NOT NULL;
CREATE UNIQUE INDEX UNIQ_1483A5E9C05FB297 ON users (confirmation_token);
```

- die beiden Skripte müssen nur **einmal** auf einer Umgebung ausgeführt werden
- um die Produktiv-Umgebung auch auf diesen Stand zu bringen, muss der gleiche Prozess durchgeführt werden (vorher lokal testen)
