### ISSUE TITLE
Offerten Formatierung II

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#67]
Reporter: Zivi

---

The generated PDFs of offers (Offerten) currently have the following formatting issues:

* [x] shortDescription (Kurzbeschreibung) is a textarea, but newlines aren't respected in rendering. Change it to a one-line input field.
* [ ] The address field is populated from the linked Customer entity. This is problematic for historical reasons in case the customer ever changes address. Also, the current Customer entity doesn't support an "Adresszusatz" field for things like Postfächer. To solve both of these issues, create an address textarea that is saved on the offer. The first time the offer is created, prefill the address from the current customer. When the pdf is rendered, use this address field as-is. This gives the user complete control over how the address in the PDF is formatted.

**Comment by cookiecavekeeper** [comment]
shortDescription is fixed in 84df8ae0c998670a9851151bd27bdddd2b362526

**Comment by cookiecavekeeper** [comment]
Abklären:

- gibt es bedarf für ein Adresszusatz Feld? (Postfach?)
- das Umstellen auf die Adresse der Offerte (nicht mehr der des Kunden) kann via E-Mail allen mitgeteilt werden

**Comment by cookiecavekeeper** [comment]
Entschieden:

 - Kanton kommt weg
 - Nummer in Strasse mergen
 - Adresszusatz hinzufügen

**Comment by cookiecavekeeper** [comment]
- [ ] überprüfen ob in Rechnung gleiches Problem besteht
