### ISSUE TITLE
Wird ein Projekt (soft)gelöscht, kann die Mutter-Offerte nicht mehr angezeigt werden

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#71]
Das *project_id* Feld in der *offers* Tabelle zeigt immer noch auf das Projekt, und das Backend will dies beim Laden der Offerte irgendwo auflösen und fällt dabei auf die Nase.

* beim Soft Delete das Feld auf *null* setzen oder 
* beim Laden das nicht-Auffinden des Projekts behandeln (besser)

**Comment by swoadmin** [comment]
https://sentry.io/swo/dime/issues/431723367/

**Comment by tourn** [comment]
Fixed in 03f95fbb8cf5efbc2acb714a86759a5b18b15040
