### ISSUE TITLE
Zu Timeslices soll eine Kurzbeschreibung hinzugefügt werden können

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#72]
Reporter: Andi

Diese sollen im Aufwandsbericht (/reports/expense) erscheinen

**Comment by cookiecavekeeper** [comment]
Die Kurzbeschreibung soll neu nicht mehr pro timeslice, sondern pro Projekt und Tag erstellt werden können.  
Also wird eine neue Tabelle / Entität erstellt: `project_comments`

**Comment by cookiecavekeeper** [comment]
Nach Sitzung:  

- Kommentar ist `textarea` (mehrere Zeilen)
- Kommentar spannt ganze Breite des PDF's
- Kommentar erstellen Formular syncen mit Timeslice erstellen Formular (Formulare kombinieren)
- Mail an alle wenn Feature fertig
