### ISSUE TITLE
"Rabattierbar" Feld von Offertenpositionen entfernen

### ISSUE THREAD

**Issue by Toasterson** [stiftungswo/Dime#8]
The Discountable Property is currently not evaluated when discaounts are calculated.

**Comment by tourn** [comment]
Das Feld macht aktuell effektiv überhaupt nichts. Was ist überhaupt die Idee dahinter?

 Wird das noch speziell für die Buchhaltung verwendet? (Glaub ich nicht, da es nicht mal irgendwo ausgedruckt wird)

Können Rabatte auf Rechnungen diesen Wert nicht überschreiten? Das wäre aber schwierig so, da das Feld nur auf Offertenpositionen ist und nicht auf Projekte/Rechnungen propagiert wird.

**Comment by Toasterson** [comment]
War ursprünglich für die Skonto abrechnung gedacht. Manche Projekte können Skonto haben manche nicht.

**Comment by tourn** [comment]
Wird nicht verwendet und kann entfernt werden.

**Comment by cookiecavekeeper** [comment]
In 5c9b8799 implementiert
