### ISSUE TITLE
Komponenten sollen Annotations für Bindings verwenden

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#84]
Momentan wird manchmal `@Component(map: ...)` und manchmal `@NgTwoWay` und Freunde. Für das Binding verwendet.

 Zumal mit beiden dasselbe erreicht werden kann, sollten alle Komponenten dieselbe Strategie verwenden. Wir tendieren zu den Annotations, zumal diese besser verständlich sind wie die `=>!` Syntax von `map`.

**Comment by cookiecavekeeper** [comment]
Auf angular4 Branch umgesetzt
