### ISSUE TITLE
Absenderadressen aus Konfiguration ziehen

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#87]
Im *parameters.yaml* ist die Absenderadresse konfiguriert, und wird teilweise auch für das Generieren von PDFs verwendet - aber mindestens im Offer und Invoice PDF stehen teilweise noch hart codierte werte drin. Diese sollten durch die Werte aus der Konfiguration ersetzt werden.

**Comment by cookiecavekeeper** [comment]
[Hier](https://github.com/stiftungswo/Dime/commit/2ac3d022e1e4515e0937288058a46902ca022c2b#diff-9604966b6332e862cfd1776cf88a7bde) wurden die dynamischen Werte durch fixe ersetzt.

Wir müssen erst abklären wieso das damals so entschieden wurde.

Allerdings können wir sowieso die Werte auslagern, auch wenn sie von den Vorhandenen getrennt werden müssen.

**Comment by tourn** [comment]
Nach einer Besprechung mit Andi sind wir dazu gekommen, das Feld wie zuvor wieder aus der Konfiguration abzufüllen. Je weniger Firmenspezifische Daten im Code, desto besser.
