### ISSUE TITLE
Default-Wert für Gewicht in Kostenstellen

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#92]
Wird eine Kostenstelle zur Rechnung hinzugefügt, kann das Gewicht komplett weggelassen werden. Dies führt dann zu einer Verteilung von "NAN%" auf dem Ausdruck. - Order zu einer Div/0 Exception beim Erstellen des PDFs. Im Optimalfall sollte beim Erstellen des Eintrags das Feld schon mit einem Wert gefüllt werden.

Alternativ muss das Einfüllen des Wertes mit besserer Validierung erzwungen werden.

**Comment by cookiecavekeeper** [comment]
Neuer Default-Wert ist 100 und wird im Frontend gesetzt  
80fbc75373ba00e425ed43513c674144f305cb4c

**Comment by swoadmin** [comment]
https://sentry.io/swo/dime/issues/436432349/

**Comment by swoadmin** [comment]
https://sentry.io/swo/dime/issues/435150712/
