### ISSUE TITLE
Einzahlungsschein Ausdruck Browserkompatibilität

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#94]
Je nach Programm, das das PDF ausdruckt, landet der Einzahlungsschein nicht am richtigen Ort auf Papier. Hier sollte erforscht werden, mit welcher Software dies richtig funtkioniert und entsprechend dokumetiert/geflickt werden.

Bei Andi scheint es auf Chrome richtig zu funktionieren.

**Comment by cookiecavekeeper** [comment]
Beim Drucker liegt eine Anleitung und auf dem Netzlaufwerk unter `/Administration/Infrastruktur_Werkzeuge_Maschinen/Gebrauchsanweisungen/Aleitung zum Drucken mit dem Epson:Anleitung zum Drucken aus dem Dime.docx` eine andere.

Allerdings nach etwas Testen auf meiner Maschine mit den Standarteinstellungen bin ich zum folgendem Schluss gekommen:

- Die Anleitung beim Drucker scheint recht gut zu funktionieren (Über den Browser drucken, keine Skalierung / Skalierung auf 100%)
- Bei mir druckt Safari am besten (das komplette Gegenteil zu dem was in der Anleitung auf dem Laufwerk steht) und die anderen Programme immer noch akzeptabel (für Menschen, möglicherweise nicht für Maschinen)
- Es zeigt sich kein klares Muster das man dokumentieren / konfigurieren könnte

Solange nicht zu viele Rechnungen gedruckt werden müssen und das Problem nicht zu oft auftritt, sollte es beim Auftreten analysiert werden

**Comment by tourn** [comment]
> sollte es beim Auftreten analysiert werden
