### ISSUE TITLE
Feriensaldo für ü50 Mitarbeiter anpassen

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#96]
Reporter: Andi

---

Einige Mitarbeiter sind jetzt ü50 und bekommen somit 25 Ferientage im Jahr. Auf der Mitarbeiterliste kann das Feriensaldo angepasst werden - es ist jedoch nicht klar, ob dies Rückwirkende Folgen auf die bestehenden Zeitperioen hat.

Falls dies der Fall sein sollte, wäre ein Workaround, für die betroffenen Mitarbeiter einen neuen Account zu erstellen.

**Comment by cookiecavekeeper** [comment]
In dbd636859e6aa092f2800678beef9489db919d82 hinzugefügt
