### ISSUE TITLE
Frontend Migration

### ISSUE THREAD

**Issue by tourn** [stiftungswo/Dime#98]
Ansprechperson: Andi

AngularDart v1 ist unmaintained und schlecht dokumentiert. Es soll eine Auffrischung der Technologie für das Dime Frontend evaluiert werden. Die verschiedenen Varianten sollen evaluiert und der zeitliche Aufwand geschätzt werden.

Kandidaten:

### Motivation
Die Sprache bleibt dieselbe, aber die Frameworkversion wird auf die aktuelle und weiterentwickelte Version upgegradet. Somit profitiert man von den aktuellen neuen Dokumentationen und neuen Features, die entwickelt werden. Bestehender Code und Projektstruktur können weitgehend wiederverwertet werden.

### Evaluation

Die Hammock Library musste angepasst werden, funktioniert aber jetzt soweit. Login, ServiceOverview, ServiceEdit funktionieren soweit. Die Struktur von Code und Templates konnte fast 1:1 übernommen werden.

Code auf Branch https://github.com/stiftungswo/Dime/tree/angulardart-4-evaluation

Voraussichtlicher Zeitaufwand: 4 Wochen

#### Pro

* gleiche Sprache
* gleiches Framework
* bessere Dokumentation für Basics
* wir profitieren von aktuellen Neuerungen in der Dart / Angular / AngularDart Welt

#### Contra

* einige Features müssen nachgebaut werden (Http Service, Template Filter)
* Dokumentation für fortgeschrittene Features lässt noch viel zu wünschen übrig

### Motivation
Die Technologie bleibt ähnlich, aber anstatt der Dart Version wird die standard Typescript Version des Frameworks verwendet, das eine grössere Community und somit mehr Support und Zukunftssicherheit bietet.

### Motivation
Der Vorteil hierbei wäre eine Vereinigung  der Frontend Technologien, die in der Stiftung SWO entwickelt werden, da iZivi momentan mit Inferno läuft. Die Einstiegshürde für neue Zivis würde somit verringert.

#### Pro

* gleiche Sprache / Framework wie im iZivi
* hervorragende Dokumentation
* viele moderne Tools / Libraries

#### Contra

* Umstieg auf "neue" Sprache
* Umstieg auf neues Framework
* grosse Teile der Applikation müssen neu gebaut werden (Hammock ersatz)
* da react nur einen kleinen Aufgabenbereich hat, müssen viele Libraries selbst geschrieben / von der Community genommen werden

**Comment by cookiecavekeeper** [comment]
Migration auf AngularDart 4 ist von Andi abgesegnet worden, allerdings sollen wir noch analysieren ob es sich lohnt auf AngularDart 5 zu warten / migrieren.

AngularDart 5 soll demnächst releast werden, wartet allerdings auf den stable Release on Dart SDK 2 (Dart 2).

Der Release von Dart 2 wurde [angekündigt](https://medium.com/@asandholm/announcing-dart-2-80ba01f43b6) aber es existieren noch keine Downloads / Tags / Dokumentationen auf der Offiziellen Homepage etc...

Mit Sicherheit könnte man also zu AngularDart auf Dart 1.* migrieren und dabei folgendes im Auge behalten um auf dem besten Weg zu sein AngularDart 5 und Dart 2 benutzen zu können:

* [dartdevc](https://webdev.dartlang.org/tools/dartdevc) benutzen; dadurch ["Strong Mode"](https://www.dartlang.org/guides/language/sound-dart) kompatibel sein
* die Tips zum Benutzen von dartdevc im Ausblick auf Dart 2 befolgen: [Dart 2](https://www.dartlang.org/dart-2) [dartdevc](https://webdev.dartlang.org/tools/dartdevc#preparing-your-code)
* die Changelogs von angular, angular_router und angular_forms berücksichtigen:
  * [AngularDart 5 Docs](https://webdev-dartlang-org-dev.firebaseapp.com/angular)
  * [angular changelog](https://pub.dartlang.org/packages/angular/versions/5.0.0-alpha+5#-changelog-tab-)
  * [angular router changelog](https://pub.dartlang.org/packages/angular_router/versions/2.0.0-alpha+5#-changelog-tab-)
  * [angular forms changelog](https://pub.dartlang.org/packages/angular_forms/versions/1.0.1-alpha+5#-changelog-tab-)
  * [dart webdev guides changelog](https://webdev-dartlang-org-dev.firebaseapp.com/changelog) 
  * [diff of changes from the old to the new docs](https://github.com/dart-lang/site-webdev/commit/68524eb3e91364762c9d7510f95c75673a183d44)

Wir könnten aber darauf warten das alle tools / libraries offiziell mit Dart 2 / AngularDart 5 support releast sind.  
Allerdings is es auch gut möglich, das dies während der Migration passiert und wir so schon anfangen können.
